### ISSUE TITLE
"Properties"

### ISSUE THREAD

**Issue by WeHappyFew1** [Autodesk-Forge/viewer-react-express-headless#11]
Hi!

I see that you have modified the "Properties" by embedding the "Properties" from the Toolbar into the viewer (you changed the UI and put it on an absolute position in the upper right). This looks so much more cleaner than the original "Properties" tab. How did you do this using Redux to handle states for Properties metadata? Can I take a look at this somewhere in the code?

**Comment by jaimerosales** [comment]
Hi,

Glad you liked it, Sure thing take a look at the following lines. So just to be clear, I'm not embedding the properties, I'm getting the model properties based on the dbid selected and recreating a new table with the information to be passed on. I also filter the categories since sometimes your models do not have any properties in specific categories, one way to compare it is, open the House model and the Race Car model you will see they have different properties being filled up. Usually AEC models tend to have a lot more metadata than manufacturing models. 

Any way, here are the lines. 
Here is the Reducer https://github.com/Autodesk-Forge/viewer-react-express-headless/blob/master/src/reducers/viewerReducer.js#L7 

Here are the actions https://github.com/Autodesk-Forge/viewer-react-express-headless/blob/master/src/actions/viewerActions.js

And here is where I launch at the time the Event AGGREGATE_SELECTION_CHANGED_EVENT happens.
https://github.com/Autodesk-Forge/viewer-react-express-headless/blob/master/src/components/Viewer/Viewer-helpers.js#L74

Which calls the following function. https://github.com/Autodesk-Forge/viewer-react-express-headless/blob/master/src/components/Viewer/Viewer-helpers.js#L109

Hope this helps, cheers!

**Comment by WeHappyFew1** [comment]
Thanks a lot for the explanation!

I've got another question. The car you're using in the demo has an insanely nice looking render. My renders looks very draft-ish. How can I improve the render like this?

**Comment by jaimerosales** [comment]
The car I'm using is an Inventor model which already has the materials looking like this. I'm not doing anything special to the rendering, at this time is not available. What type of File are you using? 
Maybe thinking about using one of our latest Viewer version can improve the look of your model.
